Exception.ShowMessageBox: Show full stack trace
Previously, it would only show the inner stack trace and drop the outer
stack trace.

After this commit, it shows the entirety of the stack trace. While the
first line may be confusing, as it now shows another exception than
before, it is more useful to be able to see the entirety of the reason.

Seen below:

Before:

> System.InvalidCastException: Unable to cast object of type 'Wrapper`1[OpenTabletDriver.Plugin.Tablet.TabletReport]' to type 'OpenTabletDriver.Plugin.Tablet.TabletReport'.
     at Eto.Forms.ThemedControls.ValueTypeWrapper.Wrapper`1.get_Value()
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
     at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

After:

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   ---> System.InvalidCastException: Unable to cast object of type 'Wrapper`1[OpenTabletDriver.Plugin.Tablet.TabletReport]' to type 'OpenTabletDriver.Plugin.Tablet.TabletReport'.
     at Eto.Forms.ThemedControls.ValueTypeWrapper.Wrapper`1.get_Value()
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
     at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
     --- End of inner exception stack trace ---
     at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
     at Eto.PropertyInfoDescriptor.GetValue(Object obj)
     at Eto.Forms.ThemedControls.ThemedPropertyGrid.PropertyItem.GetPropertyValue(Object instance)
     at Eto.Forms.ThemedControls.ThemedPropertyGrid.GetValue(PropertyItem propertyItem)
     at Eto.Forms.ThemedControls.ThemedPropertyGrid.PropertyItem.get_Value()
     at Eto.Forms.ThemedControls.ThemedPropertyGrid.PropertyItem.get_HasValue()
     at Eto.Forms.ThemedControls.ThemedPropertyGrid.PropertyItem.EnsureChildren()
     at Eto.Forms.ThemedControls.ThemedPropertyGrid.PropertyItem.Eto.Forms.IDataStore<Eto.Forms.ITreeGridItem>.get_Count()
     at Eto.GtkSharp.Forms.Controls.GtkTreeModel`2.IterHasChild(TreeIter iter)
     at Gtk.TreeModelAdapter.IterHasChild_cb(IntPtr inst, IntPtr iter)